### ISSUE TITLE
Make this typesafe?

### ISSUE THREAD

**Issue by davelosert** [sincovschi/react-flat-providers#1]
Hi @sincovschi,

first of all great work with this, thanks so much for sharing and providing a npm package! 🙂 

I was actually solving the same problem for an example project of a webinar recently, and I thought about putting it into npm. That's how I came across your library.

Our approaches are not too different - yet there is a subtle difference that I am missing here: typesafety in the provders-array-definition.

I got this to work (after several hours though 😅) by using a factory function that is able to infer the `ComponentProps` of the given provider.
 
You can see an exmaple of how that looks here:
https://github.com/thenativeweb/tlre2021/blob/main/src/AppProviders.tsx

And my implementation of the whole thing is this:
https://github.com/thenativeweb/tlre2021/blob/main/src/utils/FlatProviders.tsx

To cut a long story short:
I thought it would be way better to join forces rather than publishing yet another npm-package with a slightly different name and behaviour (there are enough of those already 😉).

Would you be open to me creating a pull request in this repository and merging our two approaches?

Thanks in advance!

**Comment by sincovschi** [comment]
Hello @davelosert,
first of all, sorry for the very delayed response... my current employer is using BitBucket...
and second, of course, I'm open to collaborating.
The project is a bit rusty, I'm working a lot with Vue3 and some Angular lately, hope to return to React :)
So, of course, I would be happy to have this repository updated.
Thanks a lot.

About the typesafety, I'm not quite getting it.
My VSCode is showing everything right without problems.
My type definition of `Providers` is equivalent to your function `providerFrom`.
Could you please elaborate on the issue?

**Comment by davelosert** [comment]
Hi @sincovschi , 

no problem. As you can see I also sometimes take some time to respond, sorry for that.
I am glad to hear that you are open to collaboration. 🙂 

Regardings typesafety:
The difference is for the props of the providers: In your current version, the second tuple of a given provider-definition can be any object as it resolves to `unknown` - in my version it will only allow the actual props of the provider.

Taking your example, I can put whatever I like into the props passed to the `Booleanprovider`:

```tsx
    <FlatProviders
      providers={[
        NumberProvider,
        [BooleanProvider, {  initialValue: 'this is not allowed as it is a string - but will not raise a compiler error' }],
        [StringContext.Provider, { value: 'Hello world!' }]
      ]}
    >
      <App />
    </FlatProviders>
)
```

With my Version, it would look like this:

```tsx
    <FlatProviders
      providers={[
        providerFrom(NumberProvider),
        providerFrom(BooleanProvider, { initialValue: 'this will raise a typescript error as a boolean is expected' })
        providerFrom(StringContext.Provider, { value: 'Hello world!' })
      ]}
    >
      <App />
    </FlatProviders>
```

This would fail on compilation.

So if you are okay I'd open a PR within the next days.

**Comment by sincovschi** [comment]
@davelosert, that sounds very interesting.
What do you think about introducing functional wrapping as another option, instead of forcing it?

Like having appended to my type definition of `Provider` your function `providerFrom`.

I think this will leave users to decide their own way to enforce types.

In code it adds one additional `if ('function' === typeof provider)` before your code.

Can you open the PR and from there we can together polish it?

To speed up things we can schedule a meet.google or something like that.

**Comment by davelosert** [comment]
Hi @sincovschi : Great Idea! Let's do it like this.

However, I am not sure if I'll be able to do anything this week as I am quite swamped - but I will try to maybe send a first PR on the weekend or beginning of next week. Then we can also schedule a little chat 🙂

**Comment by sincovschi** [comment]
OK, that sounds good.

**Comment by davelosert** [comment]
# Todos after our call

@sincovschi 
- Remove `example` directory and move it to Stackblitz

@davelosert
- Add GitHub Actions for PR and Publish Workflows
- Add Dependabot for automatic dependency updates
- Simplify ESLint Plugins

**Comment by sincovschi** [comment]
We should move this to do into a separate issue.
https://github.com/sincovschi/react-flat-providers/issues/3

**Comment by davelosert** [comment]
@sincovschi : With #8 , the last todo from this list is done.
Should we then do a merge to the main-branch and release the thing or do you want to put in the stuff suggested in #3 first?

**Comment by sincovschi** [comment]
@davelosert - I think It's good to release. But I want to add the Chain feature. I would like a lot to have this used in a project.
