### ISSUE TITLE
Proposal for ver 2.0.0

### ISSUE THREAD

**Issue by sincovschi** [sincovschi/react-flat-providers#3]
- [x] Create chainable flat providers method.

```
const FlatProviders: FlatProviders = MakeFlatProviders
    .add(NumberProvider)
    .add(BooleanProvider, { initialValue: true })
    .create();
```

**Comment by sincovschi** [comment]
3. Maybe create pipe flat provider: https://stackblitz.com/edit/react-ts-nsqhzo

**Comment by sincovschi** [comment]
4. Update Stackblitz example, once v2 is published.

**Comment by sincovschi** [comment]
- [ ] @davelosert - can you update readme.md: Solution section with a new sub-section, with usage of `makeProvider` ?

**Comment by davelosert** [comment]
@sincovschi : sorry for leaving you hanging so long without an answer. I had a little surgery going on that kept me from working.

I will take care of this within the next days. 🙂
